### ISSUE TITLE
Remove dependence on `TRUE_VALUES`

### ISSUE THREAD

**Issue by seanpdoyle** [calebthompson/time_for_a_boolean#10]
https://github.com/rails/rails/commit/a502703c3d2151d4d3b421b29fefdac5ad05df61 removes the  `ActiveRecord::ConnectionAdapters::Column::TRUE_VALUES` definition, which [breaks the `.time_for_a_boolean`method](https://github.com/calebthompson/time_for_a_boolean/blob/d5c66c56f91b15c25a2166e0b535219aa1237179/lib/time_for_a_boolean.rb#L16).

![True Value](http://ww3.truevalue.com/Portals/_default/Image%20Libraries/HomeFeature/general/Hardwarian%20Man.jpg)

**Comment by dgrosenblatt** [comment]
Maybe we could just add a constant to this gem with the same values?
```
TRUE_VALUES = [true, 1, '1', 't', 'T', 'true', 'TRUE', 'on', 'ON'].to_set
```

The rationale for removing it from Rails is a preference for  `a small set of "falsy" values and all others are "truthy" matching Ruby's semantics.` ie, the opposite of what this gem does. Regardless of the merits of that argument, following suit in this gem would break apps that have been depending on being able to do `object.deleted = 'foo'` or other non boolean values to set time_for_a_boolean columns to true.

**Comment by edwardloveall** [comment]
I created a PR to fix this. Do either of you have time to take a look? https://github.com/calebthompson/time_for_a_boolean/pull/13
