### ISSUE TITLE
Add default scopes for values if enabled

### ISSUE THREAD

**Issue by andy4thehuynh** [calebthompson/time_for_a_boolean#11]
Something as easy as an options hash for `time_for_a_boolean` method. 

`scopes: enabled` could generate:

```
scope :deleted, ->{ where.not(deleted_at: nil) }
scope :not_deleted, ->{ where.(deleted_at: nil) }
```

Would adding this benefit this project? Forked it and curious if this is worth putting a PR.

**Comment by calebthompson** [comment]
Yeah I'd consider a PR.

**Comment by Spone** [comment]
Hi @calebhearth @andy4thehuynh I need this as well so I opened a PR #17
