### ISSUE TITLE
Support for update_all

### ISSUE THREAD

**Issue by edwardloveall** [calebthompson/time_for_a_boolean#6]
As far as I can tell there's no support for `update_all`, eg:

```ruby
Task.update_all(complete: true)
```

Would this be a good fit for the gem?

**Comment by calebthompson** [comment]
It could be, yeah. `update_all`, I believe, issues SQL directly rather than going through the instance methods, so it would have to be something like `UPDATE tasks SET complete_at=current_timestamp` at the class level. Might make more sense to define `complete_all` as a class method or something similar.

Another consideration is that there's been interest in having scopes defined, so it could make sense to define it on the scope instead.

**Comment by edwardloveall** [comment]
I like the scope idea, since scope can be `Task.all` or `Task.where(...)`. That way it could update a subset the same as it does all. I think it's what I originally meant but couldn't articulate.

```ruby
tasks = Task.where(user: edward)
tasks.update_all(complete: true)
```

I'd love to take a shot at this but I'm not sure where I'd start. My knowledge of AR internals is very weak. Is this something you'd be willing to pair on some day?

**Comment by calebthompson** [comment]
Yeah I'd be down, but I'm not sure when I'll be available.

**Comment by calebthompson** [comment]
Basically you need to just define a class method that does `update_all(complete_at: Time.current)` and that will be operable on any scope, including default `all`.

**Comment by edwardloveall** [comment]
Cool. Yeah I have time on Friday afternoons if that's helpful. Or after work hours (east coast)

**Comment by edwardloveall** [comment]
Maybe I'll try and hack something together this Friday and ping you if I get stuck

**Comment by calebthompson** [comment]
Sounds good man!

**Comment by edwardloveall** [comment]
Took a stab at this and didn't get too far. Problem I ran into is I'm not sure what method to make where. Since `update_all` is [called on](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/relation.rb#L327) an ActiveRecord::Relation, do I need to add a method to that? Or maybe somewhere in [sanitize_sql_hash_for_assignment](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/sanitization.rb#L106)?

Both of those approaches seem wrong to me and I think I might be missing something.

**Comment by calebthompson** [comment]
In the module we've already defined, you should be able to add a class level method. Our module is mixed into Rails models, whose class methods are available on ActiveRecord::Relation via delegation.

**Comment by edwardloveall** [comment]
So I've tried a couple things so far:

* Defining `self.update_all` on a class. I tried this, but it didn't seem to work. For example just working with an existing project, I put a `binding.pry` in the method body but when called, it seems to call straight through to the method on the ActiveRecord::Relation class.
* Defining methods like `update_all_completed(value)`. This would be pretty lame. You'd have to call `tasks.update_all(name: 'foo').update_all_completed(true)` or something. Not better than just `.update_all(completed_at: Time.current)`

I haven't yet tried overriding `update_all` on the ActiveRecord::Relation class it self. Any advice?

**Comment by calebthompson** [comment]
Yeah that makes sense. I haven't dug into it, but I'd assume that ActiveRecord::Relation has a method_missing to go to the class, so defining update_all itself wouldn't work. It would also be problematic since we'd clobber our own method for classes with multiple boolean times.

What about `self.mark_all_#{name}`?

**Comment by edwardloveall** [comment]
Seems totally possible to do that, but I kind of wonder if it's worth it. You'll have to use `Time.current` with `update_all` still, or tack a bunch of `mark_all_*` to the end. Kind of thinking it's not worth it.

**Comment by calebthompson** [comment]
Cool, I'm gonna close if that's your opinion (mine isn't strong either way).
