### ISSUE TITLE
Including dates?

### ISSUE THREAD

**Issue by drapergeek** [calebthompson/time_for_a_boolean#8]
I was considering starting a branch/pr to allow the user to pass a key for the name of the column so that you could also use this for dates:

```ruby
time_for_a_boolean :stale, :stale_on
```

Is there a reason you wouldn't want this ability? I'd like to use this when I'm storing pure date columns, not date/time but I'm curious if there is a reason I shouldn't do that

**Comment by calebthompson** [comment]
I like the idea of supporting dates and would love to see a PR to add them.

What do you think of making the second argument a "type" which defaults to date time? So your example would be "tfab :stale, :date" and :date tells tfab to set a _on column rather than a _at.

**Comment by drapergeek** [comment]
>What do you think of making the second argument a "type" which defaults to date time? So your example would be "tfab :stale, :date" and :date tells tfab to set a _on column rather than a _at.

Depends on your theory. If we're going to assume people always follow convention, then I'd go with your way. I think having the flexibility to name your column as you prefer is nice.

Note: If there are other functions that need to change other than just the column we check, then I would prefer your solution.

**Comment by calebthompson** [comment]
How we set the time is the only thing I can think of that would change behavior possibly. We set with DateTime.now I think. Will Rails convert that? Probably.

Setting a custom column name is a different feature I think, but if that feature gets us date support for free I don't have a problem with that. Write a good commit message explaining how that works of course.
